export const fuelStations = [
  {
    id: 0,
    name: "Hass",
    location: "Kampala, Uganda",
    petrolPrice: 5678,
    dieselPrice: 5300,
    logo: require("../assets/images/hass.png"),
  },
  {
    id: 1,
    name: "Oryx",
    location: "Kampala, Uganda",
    petrolPrice: 5480,
    dieselPrice: 5300,
    logo: require("../assets/images/oryx.png"),
  },
  {
    id: 2,
    name: "Rubis",
    location: "Kampala, Uganda",
    petrolPrice: 5220,
    dieselPrice: 5300,
    logo: require("../assets/images/rubis.png"),
  },
  {
    id: 3,
    name: "Shell",
    location: "Kampala, Uganda",
    petrolPrice: 5750,
    dieselPrice: 5300,
    logo: require("../assets/images/shell.png"),
  },
  {
    id: 4,
    name: "Total",
    location: "Kampala, Uganda",
    petrolPrice: 4700,
    dieselPrice: 5300,
    logo: require("../assets/images/total.png"),
  },
  {
    id: 5,
    name: "Hass",
    location: "Kampala, Uganda",
    petrolPrice: 5230,
    dieselPrice: 5300,
    logo: require("../assets/images/stabex.png"),
  },
];
